# Generated by Django 5.0.6 on 2024-05-24 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wikmapp", "0002_customuser_note_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
